### PR TITLE
1 - HiDPI support

### LINKED ISSUE #5: Can't always pick the right color in some zones
I noticed that, after changing the hidpi scale factor some Qt applications, including colorpick, doesn't work anymore as expected, grabbing colors/images wrongly. I suspect there is some code missing that deals with the screen scale factor. ATM I noticed only Flameshot not suffering by this issue.

This is quite a blocker for #3.

### PR DESCRIPTION
**Pull request by redtide**
I omitted something like
```cpp
// default from Qt6, see https://bugreports.qt.io/browse/QTBUG-89279
#if QT_VERSION < 0x060000
  QCoreApplication::setAttribute(Qt::AA_UseHighDpiPixmaps, true);
#endif
```
(or `AA_EnableHighDpiScaling`) because it seems even without them HiDPI works anyway, at least on my Arch system (Qt 5.15.10), so I'm not sure if needed.

You can test these changes by running something like `QT_SCALE_FACTOR=1.25 qtcreator` from the terminal.

Fixes #5.

### CODE REVIEW

File: src/colorpicker.cpp [hunk 1]
```diff
@@ -17,12 +17,32 @@ static constexpr int GRAB_RADIUS = 16;
 static constexpr int GRAB_SIZE = GRAB_RADIUS * 2 + 1;
 static constexpr int MAGNIFY = 4;
 
+static QScreen *findScreenAt(const QPoint &pos)
```
Comment (agateau) [inline src/colorpicker.cpp:20]: I think nowadays we can use `QGuiApplication::screenAt()` instead of this function. This is going to bump the minimum Qt version to 5.10, but this is fine.

File: src/colorpicker.cpp [hunk 2]
```diff
@@ -17,12 +17,32 @@ static constexpr int GRAB_RADIUS = 16;
...
+            return screen;
+    }
+    return nullptr;
+}
+
+static qreal scaleFactor()
+{
+    QScreen *screen = findScreenAt(QCursor::pos());
+    if (screen)
+        return screen->devicePixelRatio();
```
Comment (agateau) [inline src/colorpicker.cpp:33]: style: always use brackets, even for single line blocks.

```suggestion
    if (screen) {
        return screen->devicePixelRatio();
    }
```

Reminds me I need to setup clang-format for this project.

File: src/colorpicker.cpp [hunk 3]
```diff
@@ -102,20 +123,11 @@ void ColorPicker::paintEvent(QPaintEvent *event)
 void ColorPicker::emitColorChanged()
 {
     QImage image = mPixmap.toImage();
-    QColor color = QColor(image.pixel(GRAB_RADIUS, GRAB_RADIUS));
+    QColor color = image.pixelColor(GRAB_RADIUS * mScaleFactor,
+                                    GRAB_RADIUS * mScaleFactor); // introduced in Qt 5.6
```
Comment (agateau) [inline src/colorpicker.cpp:127]: Can you remove this comment? It's not useful.

**Review by agateau — CHANGES_REQUESTED** [review]
Thanks for your PR! It looks mostly good, just a few nitpicks.

File: src/colorpicker.cpp (hunk 2 above)
Comment (redtide) [reply src/colorpicker.cpp:33]: that would be great, do you have already a configuration or can I paste you one for reference?

File: src/colorpicker.cpp (hunk 3 above)
Comment (redtide) [reply src/colorpicker.cpp:127]: Sure, it was somewhat for reference as "if you are OK to have 5.6 as minimum version"

**Review by agateau — APPROVED** [review]
Looks good, thanks!
